version: 2
jobs:
  build:
    docker: 
      - image: buildpack-deps:trusty
    steps:
      # ... steps for building/testing app ...
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - setup_remote_docker:
          version: 19.03.13

     - run: |
         echo "$DOCKER_PASS" | docker login spidervex.azurecr.io --username $DOCKER_USER --password-stdin


     # build the application image
     - run: docker build -t spidervex.azurecr.io/api-gateway:v1 .

     # deploy the image
     - run: docker push spidervex.azurecr.io/api-gateway:v1
